//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonOrderItem
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public string OrderitemName { get; set; }
        public string OrderitemType { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantitiy { get; set; }
    
        public virtual AmazonOrder AmazonOrder { get; set; }
        public virtual AmazonProduct AmazonProduct { get; set; }
    }
}
