//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AmazonProduct()
        {
            this.AmazonOrderItems = new HashSet<AmazonOrderItem>();
        }
    
        public int Id { get; set; }
        public string TypeID { get; set; }
        public string ProductName { get; set; }
        public string TypeM { get; set; }
        public decimal UnitPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmazonOrderItem> AmazonOrderItems { get; set; }
    }
}
