//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APD65_63011212004Entities5 : DbContext
    {
        public APD65_63011212004Entities5()
            : base("name=APD65_63011212004Entities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AmazonOrder> AmazonOrders { get; set; }
        public virtual DbSet<AmazonOrderItem> AmazonOrderItems { get; set; }
        public virtual DbSet<AmazonProduct> AmazonProducts { get; set; }
    }
}
